import type { Metadata } from "next";
import { Sora } from "next/font/google";
import CE_Navbar from "../components/common/CE_Navbar";

import "./globals.css";

const sora = Sora({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={sora.className}>
        <CE_Navbar />
        {children}
      </body>
    </html>
  );
}
